### ISSUE TITLE
OAuthenticator http[s]_proxy issue: Tornado http client does not use http[s]_proxy env variables to make an http request

### ISSUE THREAD

**Issue by ReubenBorrison** [jupyterhub/oauthenticator#300] opened 2019-11-09 10:23 UTC
Hello

I am trying to implement a single sign on for the jupyterhub but I am not able to do so I need to bypass a proxy which I configured in hub's environment variables. But the Oauth still gives an connection refused error. 
On digging on the issue, I found out that the tornado http client used to create an http request does not use the environment proxy variable but one needs to configure it in the client. Unfortunately I was not able to find a config where I can enter the proxy information, can anybody point me to the right config?

**Comment by manics** [comment] 2020-10-13 20:00
This is a duplicate of https://github.com/jupyterhub/oauthenticator/issues/217
Unfortunately it's not resolved, but there are some workarounds in the comments.

**Closed by manics** 2020-10-13 20:00 UTC
