### ISSUE TITLE
Working configuration for generic authenticator with Keycloak

### ISSUE THREAD

**Issue by pfisterer** [jupyterhub/oauthenticator#107] opened 2017-08-18 10:46 UTC
I have tried to configure Jupyterhub to use the generic OAuth2 authentication mechanism with [Keycloak](http://www.keycloak.org/) as OAuth2 sever. However, it never redirects to it for authentication. Could you please support me and provide a sample configuration that is supposed to work? Or is there anything that I'm obviously doing wrong?

Thank you very much!
Dennis

OAuthenticator configuration in jupyterhub_config.py:
```
from oauthenticator.generic import GenericOAuthenticator
c.JupyterHub.authenticator_class = GenericOAuthenticator

c.GenericOAuthenticator.oauth_callback_url = 'https://example.com:8443/auth/realms/testrealm/protocol/openid-connect/auth'
c.GenericOAuthenticator.client_id = 'oauth-secret'
c.GenericOAuthenticator.client_secret = 'asfdsdf-dfdf-fhhfh-aed7-asdafsdfsaf'
c.GenericOAuthenticator.token_url = 'https://example.com:8443/auth/realms/testrealm/protocol/openid-connect/token'
c.GenericOAuthenticator.userdata_url = 'https://141.72.18.234:8443/auth/realms/testrealm/protocol/openid-connect/userinfo'
```

Keycloak Endpoints:
```JSON
{
	"issuer": "https://example.com:8443/auth/realms/testrealm",
	"authorization_endpoint": "https://example.com:8443/auth/realms/testrealm/protocol/openid-connect/auth",
	"token_endpoint": "https://example.com:8443/auth/realms/testrealm/protocol/openid-connect/token",
	"token_introspection_endpoint": "https://example.com:8443/auth/realms/testrealm/protocol/openid-connect/token/introspect",
	"userinfo_endpoint": "https://example.com:8443/auth/realms/testrealm/protocol/openid-connect/userinfo",
	"end_session_endpoint": "https://example.com:8443/auth/realms/testrealm/protocol/openid-connect/logout",
	"jwks_uri": "https://example.com:8443/auth/realms/testrealm/protocol/openid-connect/certs",
	"check_session_iframe": "https://example.com:8443/auth/realms/testrealm/protocol/openid-connect/login-status-iframe.html",
	"grant_types_supported": ["authorization_code", "implicit", "refresh_token", "password", "client_credentials"],
	"response_types_supported": ["code", "none", "id_token", "token", "id_token token", "code id_token", "code token", "code id_token token"],
	"subject_types_supported": ["public", "pairwise"],
	"id_token_signing_alg_values_supported": ["RS256"],
	"userinfo_signing_alg_values_supported": ["RS256"],
	"request_object_signing_alg_values_supported": ["none", "RS256"],
	"response_modes_supported": ["query", "fragment", "form_post"],
	"registration_endpoint": "https://example.com:8443/auth/realms/testrealm/clients-registrations/openid-connect",
	"token_endpoint_auth_methods_supported": ["private_key_jwt", "client_secret_basic", "client_secret_post"],
	"token_endpoint_auth_signing_alg_values_supported": ["RS256"],
	"claims_supported": ["sub", "iss", "auth_time", "name", "given_name", "family_name", "preferred_username", "email"],
	"claim_types_supported": ["normal"],
	"claims_parameter_supported": false,
	"scopes_supported": ["openid", "offline_access"],
	"request_parameter_supported": true,
	"request_uri_parameter_supported": true
}
```

**Comment by willingc** [comment] 2017-08-18 13:23
Hi @pfisterer, How are you generating the client_secret:

`c.GenericOAuthenticator.client_secret = 'asfdsdf-dfdf-fhhfh-aed7-asdafsdfsaf'`

**Comment by pfisterer** [comment] 2017-08-18 16:40
@willingc I obtained the (original) client secret from Keycloak (and verified that it is correct using curl). However, the string above is a modified version (just as the domain name does not reflect my internal settings at the university).

**Comment by pfisterer** [comment] 2017-08-19 16:15
Would it help if I supply a keycloak instance for testing?

**Comment by willingc** [comment] 2017-08-19 21:39
@pfisterer Thanks for the testing offer. I'm out of the office for the next week so I may have a delayed response.

@minrk Have you worked with Keycloak? I'm thinking that we need to add to the generic auth to support Keycloak's use of Realm.

**Comment by minrk** [comment] 2017-08-20 11:56
I haven't used the generic authenticator. @dmvieira do you have an example of a fully working generic oauth config?

@pfisterer what happens when you hit the 'Login with...' button exactly, if there is no redirect? Are there errors in the js console or the jupyterhub logs?

**Comment by dmvieira** [comment] 2017-08-20 15:06
For OAuthenticator generic integration we need to add at jupyterhub_config.py:
c.JupyterHub.authenticator_class = 'oauthenticator.generic.GenericOAuthenticator'
c.OAuthenticator.client_id # oauth2 client id for your app
c.OAuthenticator.client_secret # oauth2 client secret for your app
c.GenericOAuthenticator.token_url # oauth2 provider's token url 
c.GenericOAuthenticator.userdata_url # oauth2 provider's endpoint with user data
c.GenericOAuthenticator.userdata_method # method used to request user data endpoint
c.GenericOAuthenticator.userdata_params # params to send for userdata endpoint
c.GenericOAuthenticator.username_key # username key from json returned from user data endpoint

And export these environment variables:
OAUTH2_TOKEN_URL # the same as token_url param
OAUTH2_AUTHORIZE_URL # oauth2 provider's authorization andpoint

For more details I'll show how to integrate with generic authentication in https://conferences.oreilly.com/jupyter/jup-ny/public/schedule/detail/59400

**Comment by dmvieira** [comment] 2017-08-20 15:09
Perhaps you forgot environment variables

**Comment by patback66** [comment] 2017-09-26 22:36
Was there any resolution to this? I'm attempting a similar setup and have been running into the same issues. The button for the login page still directs to `example.com:8000/hub/login` so it won't direct the user to the Keycloak login. If I manually navigate to `example.com:8000/hub/oauth_login` I end up with an infinite redirect to `example.com:8000/hub/oauth_callback?...` and don't actually hit Keycloak's login.

**Comment by dmvieira** [comment] 2017-09-26 23:05
Are you using the environment variables?


OAUTH2_TOKEN_URL # the same as token_url param
OAUTH2_AUTHORIZE_URL # oauth2 provider's authorization andpoint

**Comment by patback66** [comment] 2017-09-26 23:21
Fixing the env variables solved the infinite redirect after navigating to `/hub/oauth_login`. Unfortunately the login url for the button on `/hub/login` still doesn't get set properly.

**Comment by dmvieira** [comment] 2017-09-26 23:58
You can use custom template paths and change login button template to redirect to correct login URL.

Here I'm using extra_template_path and template_paths at jupyter and jupyterhub configs. Then you can use your custom htmls

**Comment by dmvieira** [comment] 2017-09-27 01:37
It's strange because you should never click on login button... Oauthenticator always redirects you to authorize URL when you try to access Notebook. Please, explain me a bit more and paste your Hub and Notebook configuration

**Comment by patback66** [comment] 2017-09-27 16:06
Censored some bits but here's the config for authentication:
```
from oauthenticator.generic import LocalGenericOAuthenticator
c.JupyterHub.authenticator_class = LocalGenericOAuthenticator
c.OAuthenticator.client_id = '{client_id}'
c.OAuthenticator.client_secret = '{client_secret}'
c.LocalGenericOAuthenticator.token_url = 'https://{domain}:{port}/auth/realms/{realm}/protocol/openid-connect/token'# oauth2 provider's token url
c.LocalGenericOAuthenticator.userdata_url = 'https://{domain}:{port}/auth/realms/{realm}/protocol/openid-connect/userinfo'
c.LocalGenericOAuthenticator.userdata_method = 'GET'
c.LocalGenericOAuthenticator.userdata_params = {"state": "state"}
c.LocalGenericOAuthenticator.username_key = "preferred_username"
c.LocalAuthenticator.create_system_users = True
``` 

and env vars
```
OAUTH2_AUTHORIZE_URL=https://{domain}:{port}/auth/realms/{realm}/protocol/openid-connect/auth
OAUTH2_TOKEN_URL=https:/{domain}:{port}/auth/realms/{realm}/protocol/openid-connect/token
```

Should I be setting something like `c.Authenticator.auto_login = True` to get the intended behavior?

**Comment by dmvieira** [comment] 2017-09-27 17:52
I never used LocalGenericOAuthenticator only GenericOAuthenticator and it works great... LocalGenericOAuthenticator I don't know

**Comment by SarunasG** [comment] 2017-10-25 09:58
Hi All,

I am able to log in to Jupyterhub successfully with configuration mentioned above. (using Keycloak for authentication and GenericOAuthenticator as Oauth class), but the problem is that I am not able to logout. The only thing that happens when I click on "logout" button - I am redirected to default login page with login "Sign in with GenericOAuth2" button again. And if I click on this button I am not prompted for any credentials. 
Log record below...
`[I 2017-10-25 13:33:23.105 JupyterHub log:122] 302 GET /hub/logout → /hub/login`

It means that my session tokens/cookies are not removed, hence no call to Keycloack to end up the session is done - so I actually still remain logged in.
Am I missing anything in my jupyterhub_config.py file, should I implement my own logout handler or etc. ?

**Comment by dmvieira** [comment] 2017-10-25 11:10
Keycloak has logout callback? Use logout callback to call /logout on jupyterhub

**Comment by niveau0** [comment] 2018-03-21 15:35
Made a keycloak authenticator a while ago:
https://github.com/matipp/oauthenticator/commit/326d2617ce09749ca0c4d9a19e9651fe437e1755
but never had time to write tests for a PR, sorry

**Comment by clkao** [comment] 2018-09-09 15:31
You can create a user realm role mapper in the keycloak client, and enable auth_state.  You can then override OIDCAuthenticator's authenticate method and check for the roles that you want to whitelist.

**Comment by bellackn** [comment] 2018-09-28 14:06
Hey @clkao, thanks for your answer, this does sound much more elegant indeed... Would you mind describing in greater detail how to achieve this? I and potentially billions of other people would really appreciate it. :slightly_smiling_face:

**Comment by FCtj** [comment] 2019-02-13 06:41
Is there anyone dealing with this issue..?
1. How can I logout by clicking jupyterhub logout button?
2. How can I access directly to keycloak login page not seeing this page (url: [host]/hub/login)
![image](https://user-images.githubusercontent.com/21338864/52691940-c30c8e00-2fa5-11e9-92cd-99595c743f0d.png)

3. How can I apply @gweis 's extension solution..?

**Comment by gweis** [comment] 2019-02-20 00:03
see https://jupyterhub.readthedocs.io/en/stable/api/auth.html 

`c.Authenticator.auto_login = Bool(False)`

setting this option to True will skip the extra login page.

**Comment by ysy92618** [comment] 2019-02-20 21:46
Thanks for responding back to me.  I have already set c.Authenticator.auto_login=True.

Anyhow, we finally escalate this to our internal Okta expert yesterday and it turns out the c.GenericOAuthenticator.userdata_url = 'https://$OktaServer/oauth2/v1/clients' they provided us was incorrect.  It looks that generic.py forces Jupyterhub to call the userdata_endpoint (they said that is usually an optional step) and the correct userdata end point should be the my company’s Okta userinfo_endpoint which has a special string between oath2 and v1.

Thanks,
Shawn

**Comment by ibraheemsadiq** [comment] 2019-05-19 21:07
Request URL: http://34.219.19.59/hub/oauth_login?response_type=code&redirect_uri=https%3A%2F%2F34.219.19.59%3A8443%2Fauth%2Frealms%2Fmaster%2Fprotocol%2Fopenid-connect%2Fauth&client_id=jupyterconnection&state=eyJzdGF0ZV9pZCI6ICI4M2FiZDAzMWY3Y2E0ZWUwOTU1ZWNlZDEyOTBmMTg5MyIsICJuZXh0X3VybCI6IG51bGx9


Error 302

http://34.219.19.59 , can any one help

**Comment by ibraheemsadiq** [comment] 2019-05-19 21:16
Request URL: http://x.y.z/hub/oauth_login?response_type=code&redirect_uri=https%3A%2F%2F3.19.59%3A8443%2Fauth%2Frealms%2Fmaster%2Fprotocol%2Fopenid-connect%2Fauth&client_id=jupyterconnection&state=eyJzdGF0ZV9pZCI6ICI4M2FiZDAzMWY3Y2E0ZWUwOTU1ZWNlZDEyOTBmMTg5MyIsICJuZXh0X3VybCI6IG51bGx9

Error 302
can any one help , oauth -> generic -> little jupyterhub -> keycloak

**Comment by gabrielpatricio** [comment] 2019-06-26 22:49
Can someone please provide me the full jupyterhub_config.py file configuration for Keycloak Auth?

**Comment by saurav-bhagat** [comment] 2020-03-12 07:33
> For OAuthenticator generic integration we need to add at jupyterhub_config.py:
> c.JupyterHub.authenticator_class = 'oauthenticator.generic.GenericOAuthenticator'
> c.OAuthenticator.client_id # oauth2 client id for your app
> c.OAuthenticator.client_secret # oauth2 client secret for your app
> c.GenericOAuthenticator.token_url # oauth2 provider's token url
> c.GenericOAuthenticator.userdata_url # oauth2 provider's endpoint with user data
> c.GenericOAuthenticator.userdata_method # method used to request user data endpoint
> c.GenericOAuthenticator.userdata_params # params to send for userdata endpoint
> c.GenericOAuthenticator.username_key # username key from json returned from user data endpoint
> 
> And export these environment variables:
> OAUTH2_TOKEN_URL # the same as token_url param
> OAUTH2_AUTHORIZE_URL # oauth2 provider's authorization andpoint
> 
> For more details I'll show how to integrate with generic authentication in https://conferences.oreilly.com/jupyter/jup-ny/public/schedule/detail/59400

If I'm doing this in docker container, then the environment variables should be set using Dockerfile right?

**Comment by dmvieira** [comment] 2020-03-12 10:07
> > For OAuthenticator generic integration we need to add at jupyterhub_config.py:
> > c.JupyterHub.authenticator_class = 'oauthenticator.generic.GenericOAuthenticator'
> > c.OAuthenticator.client_id # oauth2 client id for your app
> > c.OAuthenticator.client_secret # oauth2 client secret for your app
> > c.GenericOAuthenticator.token_url # oauth2 provider's token url
> > c.GenericOAuthenticator.userdata_url # oauth2 provider's endpoint with user data
> > c.GenericOAuthenticator.userdata_method # method used to request user data endpoint
> > c.GenericOAuthenticator.userdata_params # params to send for userdata endpoint
> > c.GenericOAuthenticator.username_key # username key from json returned from user data endpoint
> > And export these environment variables:
> > OAUTH2_TOKEN_URL # the same as token_url param
> > OAUTH2_AUTHORIZE_URL # oauth2 provider's authorization andpoint
> > For more details I'll show how to integrate with generic authentication in https://conferences.oreilly.com/jupyter/jup-ny/public/schedule/detail/59400
> 
> If I'm doing this in docker container, then the environment variables should be set using Dockerfile right?

Yes, but how is your infrastructure?

**Comment by saurav-bhagat** [comment] 2020-03-23 10:11
> > > For OAuthenticator generic integration we need to add at jupyterhub_config.py:
> > > c.JupyterHub.authenticator_class = 'oauthenticator.generic.GenericOAuthenticator'
> > > c.OAuthenticator.client_id # oauth2 client id for your app
> > > c.OAuthenticator.client_secret # oauth2 client secret for your app
> > > c.GenericOAuthenticator.token_url # oauth2 provider's token url
> > > c.GenericOAuthenticator.userdata_url # oauth2 provider's endpoint with user data
> > > c.GenericOAuthenticator.userdata_method # method used to request user data endpoint
> > > c.GenericOAuthenticator.userdata_params # params to send for userdata endpoint
> > > c.GenericOAuthenticator.username_key # username key from json returned from user data endpoint
> > > And export these environment variables:
> > > OAUTH2_TOKEN_URL # the same as token_url param
> > > OAUTH2_AUTHORIZE_URL # oauth2 provider's authorization andpoint
> > > For more details I'll show how to integrate with generic authentication in https://conferences.oreilly.com/jupyter/jup-ny/public/schedule/detail/59400
> > 
> > 
> > If I'm doing this in docker container, then the environment variables should be set using Dockerfile right?
> 
> Yes, but how is your infrastructure?

Hey! How can I set this environment variables? Using Dockerfile?

**Comment by dmvieira** [comment] 2020-03-23 13:59
Or in Dockerfile with `ENV OAUTH2_TOKEN_URL https://YOUR_URL` or using docker command `docker run -e OAUTH2_TOKEN_URL='https://YOUR_URL'`

**Comment by saurav-bhagat** [comment] 2020-03-24 08:53
Thanks @dmvieira . Actually, I'm little confused regarding the setup of authentication with jupyterhub and my on-premise Oauth service. 

- Do I just need to add the variables mentioned above along with env variables?

- No where redirect uri is mentioned? So, is it of no use here?

- If I exclude the userdata variables such as params and key and url. Will this work?

- My service gives me resource URI and client ID but not client secret as github oauth gives. How can I get that?

Can you please help me out with this?
Thanks

**Comment by subhojitpaul1995** [comment] 2020-04-15 07:36
Getting the same issue as @pfisterer  after I configured Jupyterhub with Keycloak. The login mechanism is working fine, however the logout button always redirect to login URI
(/hub/logout -> /hub/login) and then on clicking "Sign in using Keycloak" it directly opens home page without any authentication. I found that the keycloak logout API is not getting called from GenericOauthenticator & that's why the SSO user session is not getting terminated.
keycloak logout URL :https://{ip}:{port}/auth/realms/jhub_realm/protocol/openid-connect/logout?redirect_uri=
OAuthenticator configuration in jupyterhub_config.py:
from oauthenticator.generic import GenericOAuthenticator
c.JupyterHub.authenticator_class = GenericOAuthenticator
c.GenericOAuthenticator.login_service = 'keycloak'
c.GenericOAuthenticator.userdata_params = {"state": "state"}
c.GenericOAuthenticator.auto_login = False
c.Authenticator.auto_login = False

and exporter this env variables,

export OAUTH2_AUTHORIZE_URL=https://{ip}:{port}/auth/realms/jhub_realm/protocol/openid-connect/auth
export OAUTH2_TOKEN_URL=https://{ip}:{port}/auth/realms/jhub_realm/protocol/openid-connect/token
export OAUTH_CLIENT_SECRET=*****************
export OAUTH_CALLBACK_URL=http://{ip}:{port}/hub/oauth_callback
export OAUTH2_USERDATA_URL=https://{ip}:{port}/auth/realms/jhub_realm/protocol/openid-connect/userinfo
export OAUTH_CLIENT_ID=jupyter-hub
export OAUTH2_USERNAME_KEY=preferred_username

Can anyone help me regarding this, how to call keycloak user session end point from jupyterhub GenericOauthenticator ?????

**Comment by meeseeksmachine** [comment] 2020-07-24 18:12
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/generic-oauthenticator-redirect-issue/4078/5

**Comment by hbuttguavus** [comment] 2020-09-09 15:43
Hi,
I am also facing an issue with logging out. Once I sign in I am unable to log out unless I go to keycloak and end the session. Only then do I get prompted to enter the username and password again. I am using the juyterhub helm chart and have the following values which work except that I can not logout. Can anyone help identify what I might be missing? Thanks.

`hub:
  extraEnv:
    OAUTH2_AUTHORIZE_URL: https://${host}/auth/realms/${realm}/protocol/openid-connect/auth
    OAUTH2_TOKEN_URL: https://${host}/auth/realms/${realm}/protocol/openid-connect/token
    OAUTH_CALLBACK_URL: https://<your_jupyterhub_host>/hub/oauth_callback
    OAUTH2_TLS_VERIFY: false
auth:
  type: custom
  custom:
    className: oauthenticator.generic.GenericOAuthenticator
    config:
      login_service: "Keycloak"
      client_id: "XXX"
      client_secret: "XXX"
      token_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/token
      userdata_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/userinfo
      userdata_method: GET
      userdata_params: {'state': 'state'}
      username_key: preferred_username`

**Comment by t20100** [comment] 2020-09-10 12:32
If that can help, I got logout with keycloak working with oauthenticator 0.11.0 with the following code:

An authenticator with a `LogoutHandler` since the default one does not handles logout against authentication service:
```
from oauthenticator.generic import GenericOAuthenticator
from jupyterhub.utils import url_path_join
from jupyterhub.handlers.login import LogoutHandler
from tornado.httputil import url_concat

class KeycloakLogoutHandler(LogoutHandler):
    """Logout handler for keycloak"""

    async def render_logout_page(self):
        params = {
            'redirect_uri': '%s://%s%s' % (
                self.request.protocol,
                self.request.host,
                self.hub.server.base_url),
            }
        self.redirect(
            url_concat(self.authenticator.keycloak_logout_url, params),
            permanent=False
        )

class KeycloakAuthenticator(GenericOAuthenticator):
    """Authenticator handling keycloak logout"""

    keycloak_logout_url = Unicode(
        config=True,
        help="The keycloak logout URL"
    )

    def get_handlers(self, app):
        return super().get_handlers(app) + [(r'/logout', KeycloakLogoutHandler)]
```

And then use the authenticator and logout URL configuration:
```
c.JupyterHub.authenticator_class = KeycloakAuthenticator
c.KeycloakAuthenticator.keycloak_logout_url = "https://example.com/auth/realms/REALM/protocol/openid-connect/logout"
```

I don't know how much that can be generalized, but when using keycloak that would be great to have the logout handled by default.

**Comment by hbuttguavus** [comment] 2020-09-11 03:27
@t20100 Thank you! Really appreciate it. The code helped me understand what I needed to do and I was able to use it in the helm chart for jupyterhub.

**Comment by manics** [comment] 2020-10-13 20:16
Hi, I'm closing this as it seems to have ended up covering several issues. There's a recent example of a working config on the Jupyter community forum:
https://discourse.jupyter.org/t/configuring-zero-to-jupyter-hub-to-use-an-arbitrary-oauth2-provider/5542/4

If anyone has a concrete idea for improving the docs please open a PR 😀

**Closed by manics** 2020-10-13 20:16 UTC

**Comment by Freir96** [comment] 2020-10-29 10:45
All those advices helped me a lot, but when I try to use OAuth 2.0 I get this message from keycloak:

> We are sorry... Invalid parameter: redirect_uri

And this is the log from keyclock server:

> 2020-10-29 10:34:58,025 WARN  [org.keycloak.events] (default task-5) type=LOGIN_ERROR, realmId=master, clientId=account, userId=null, ipAddress=10.0.2.2, error=invalid_redirect_uri, redirect_uri=http://192.168.100.1:8600/hub/oauth_callback

jupyterhub_config.py:
`host_ip = '192.168.100.1'
ip = host_ip
keycloak_guest_port = '8180'
keycloak_host_port = '8586'
keycloak_port = keycloak_host_port
c.JupyterHub.authenticator_class = GenericOAuthenticator
c.OAuthenticator.client_id = 'account' # oauth2 client id for your app
c.OAuthenticator.client_secret = '5110687d-5c91-406d-8721-2f09b11e21fe' # oauth2 client secret for your app
c.GenericOAuthenticator.token_url = "http://" + ip + ":" +keycloak_port + "/auth/realms/master/protocol/openid-connect/token" # oauth2 provider's token url
c.GenericOAuthenticator.userdata_url = "http://" + ip + ":" +keycloak_port + "/auth/realms/master/protocol/openid-connect/userinfo" # oauth2 provider's endpoint with user data
c.GenericOAuthenticator.userdata_method = 'GET' # method used to request user data endpoint
c.GenericOAuthenticator.userdata_params = {'state': 'state'} # params to send for userdata endpoint
c.GenericOAuthenticator.username_key = 'admin' # username key from json returned from user data endpoint

`
Enviromental variables:
`export OAUTH2_TOKEN_URL=http://192.168.100.1:8586/auth/realms/master/protocol/openid-connect/token
export OAUTH2_AUTHORIZE_URL=http://192.168.100.1:8586/auth/realms/master/protocol/openid-connect/auth
export OAUTH_CALLBACK_URL=http://192.168.100.1:8600/hub/oauth_callback`
Ports:
`config.vm.network "forwarded_port", guest: 8000, host: 8600
config.vm.network "forwarded_port", guest: 8001, host: 8601
config.vm.network "forwarded_port", guest: 8081, host: 8681
config.vm.network "forwarded_port", guest: 8180, host: 8586`

As you can probably see, I'm not using docker, but Vagrant. Nothing I've found helped me solve this issue.

**Comment by Freir96** [comment] 2021-02-03 13:55
@t20100 What is that Unicode() function? I can't find a unicode function with config param, and the logout does not work when I replace it with a string.

**Comment by t20100** [comment] 2021-02-03 14:35
It looks like `from traitlets import Unicode` was missing, I've added it to the sample code.

See [traitlets.Unicode](https://traitlets.readthedocs.io/en/stable/trait_types.html#traitlets.Unicode)

**Comment by Freir96** [comment] 2021-02-03 16:57
Are you sure that this is everything?
It does not seem to be working:
`[E 2021-02-03 17:30:44.074 JupyterHub app:2859]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 2856, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 2347, in initialize
        self.load_config_file(self.config_file)
      File "<decorator-gen-5>", line 2, in load_config_file
      File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 602, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 563, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/vagrant/modules/jupyterhub/jupyterhub_config.py", line 36, in <module>
        class KeycloakAuthenticator(GenericOAuthenticator):
      File "/vagrant/modules/jupyterhub/jupyterhub_config.py", line 40, in KeycloakAuthenticator
        help="The keycloak logout URL"
    TypeError: 'config' is an invalid keyword argument for this function`

**Comment by ric-art-m** [comment] 2021-02-17 01:50
In my jupyterhub_config.py i put the below settings to resolve the redirect issue 

import os

os.environ['OAUTH2_TOKEN_URL'] = 'https://{domain}:{port}/auth/realms/{realm}/protocol/openid-connect/token'
os.environ['OAUTH2_AUTHORIZE_URL'] = 'https://{domain}:{port}/auth/realms/{realm}/protocol/openid-connect/auth'
os.environ['OAUTH2_USERDATA_URL'] = 'https://{domain}:{port}/auth/realms/{realm}/protocol/openid-connect/userinfo'


from oauthenticator.generic import GenericOAuthenticator
c.JupyterHub.authenticator_class = 'oauthenticator.generic.GenericOAuthenticator'
c.GenericOAuthenticator.login_service = 'Keycloak'
c.OAuthenticator.client_id = '{client_id}'
c.OAuthenticator.client_secret = '{client_secret}'
c.GenericOAuthenticator.oauth_callback_url = 'https://{hub}/jupyter/hub/oauth_callback'
c.GenericOAuthenticator.userdata_url = 'https://{domain}:{port}/auth/realms/{realm}/protocol/openid-connect/userinfo'
c.GenericOAuthenticator.token_url = 'https://{domain}:{port}/auth/realms/{realm}/protocol/openid-connect/token'
c.GenericOAuthenticator.userdata_method = 'GET'
c.GenericOAuthenticator.userdata_params = {"state": "state"}
c.GenericOAuthenticator.username_key = "preferred_username"


However i after successfull authentication from keycloak i got SSL error below

ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)

to temporary resolve it i add this settings
c.OAuthenticator.tls_verify = False

hope this helps.

**Comment by jgato** [comment] 2021-05-11 16:05
> Hi,
> I am also facing an issue with logging out. Once I sign in I am unable to log out unless I go to keycloak and end the session. Only then do I get prompted to enter the username and password again. I am using the juyterhub helm chart and have the following values which work except that I can not logout. Can anyone help identify what I might be missing? Thanks.
> 
> ```
> hub:
>   extraEnv:
>     OAUTH2_AUTHORIZE_URL: https://${host}/auth/realms/${realm}/protocol/openid-connect/auth
>     OAUTH2_TOKEN_URL: https://${host}/auth/realms/${realm}/protocol/openid-connect/token
>     OAUTH_CALLBACK_URL: https://<your_jupyterhub_host>/hub/oauth_callback
>     OAUTH2_TLS_VERIFY: false
> auth:
>   type: custom
>   custom:
>     className: oauthenticator.generic.GenericOAuthenticator
>     config:
>       login_service: "Keycloak"
>       client_id: "XXX"
>       client_secret: "XXX"
>       token_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/token
>       userdata_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/userinfo
>       userdata_method: GET
>       userdata_params: {'state': 'state'}
>       username_key: preferred_username
> ```

using you cool exmaple it worked like a charm, but logout is not working :( Did you find the solution?

**Comment by MaisamMD** [comment] 2021-09-07 08:27
Hi everyone,

I am using the generic authenticator to integrate jupyterhub with an external OIDC provider. When I press the login button I will be redirected to the OIDC provider login page. When I log in using my credentials, I don't redirect back to the jupyterhub and I will stay on my page on the OIDC provider side. Any hint to tackle this issue?
This is the part of my config file related to authentication :

```
c = get_config()
import os
# use Generic OAuthenticator for local users
from oauthenticator.generic import GenericOAuthenticator
c.Application.log_level = 'DEBUG'

c.JupyterHub.authenticator_class = GenericOAuthenticator
c.GenericOAuthenticator.client_id =  os.environ['IAM_CLIENT_ID']
c.GenericOAuthenticator.client_secret = os.environ['IAM_CLIENT_SECRET']
c.GenericOAuthenticator.token_url = os.environ['OAUTH2_TOKEN_URL']
c.GenericOAuthenticator.userdata_method = 'GET'
c.GenericOAuthenticator.userdata_params = {"state": "state"}
c.GenericOAuthenticator.login_service = 'ESCAPE IAM'
c.GenericOAuthenticator.oauth_callback_url = os.environ['OAUTH_CALLBACK_URL']

```

**Comment by navdeepbansal** [comment] 2021-09-14 10:56
i am bale to integrate keycloak with jupyterhub but still not able to figure it out how can we restrict users with particular keycloak role to access jupyterhub.

**Comment by navdeepbansal** [comment] 2021-09-14 12:35
> Hey @clkao, thanks for your answer, this does sound much more elegant indeed... Would you mind describing in greater detail how to achieve this? I and potentially billions of other people would really appreciate it. 🙂

Hi, could you please let me know if you have got the solution ?

**Comment by geoffo-dev** [comment] 2022-04-01 16:02
Hello @navdeepbansal - are you able to post the solution?

As for group restriction - have you seen this?

https://github.com/jupyterhub/oauthenticator/tree/main/examples/generic - there is a section at the bottom about groups

**Comment by YuhangLYH** [comment] 2022-09-27 15:46
> 
Hi, have you tried using allowed_groups?

`c.GenericOAuthenticator.allowed_groups = ["KEYCLOAK-GROUP"]` This works in our case
