### ISSUE TITLE
Github Authentication Redirects to 404 Page not found

### ISSUE THREAD

**Issue by Akmoore7** [jupyterhub/oauthenticator#193] opened 2018-06-07 16:06 UTC
Currently jupyterhub is running when logging in using PAM, but we are trying to configure github authentication. When running "Sign in with Github" shows up but when clicked it takes the user to "https://github.com/login/oauth/authorize?redirect_uri=https%3A%2F%2Fjupyter2.uiuc-bdeep.org%2Fhub%2Foauth_callback&client_id=&response_type=code&state=eyJuZXh0X3VybCI6ICIiLCAic3RhdGVfaWQiOiAiZTdjNGU1YTkzZGU0NDViMGE4ZWU0NzY3ODY1Y2I1YmUifQ%3D%3D"

This is our config file:
# Configuration file for jupyterhub

c.JupyterHub.ssl_key = '/etc/letsencrypt/live/jupyter2.uiuc-bdeep.org/privkey.pem'
c.JupyterHub.ssl_cert = '/etc/letsencrypt/live/jupyter2.uiuc-bdeep.org/fullchain.pem'
c.JupyterHub.port = 443

c.Spawner.notebook_dir = '~/assignments'

from oauthenticator.github import GitHubOAuthenticator
c.JupyterHub.authenticator_class = GitHubOAuthenticator
c.MyOAuthenticator.oauth_callback_url = 'https://jupyter2.uiuc-bdeep.org/hub/oauth_callback'
c.MyOAuthenticator.client_id = '7959f7faeee887a00c71'
c.MyOAuthenticator.client_secret = 'Client Secret'
c.Authenticator.whitelist = {'akmoore7','danielrychel' }
c.Authenticator.admin_users = {'Akmoore7','danielrychel'}

I'm not sure what is going on at the moment, I made sure the client id was inputted correctly. There are no errors just this log statement:
302 GET /hub/oauth_login?next= → https://github.com/login/oauth/authorize?redirect_uri=https%3A%2F%2Fjupyter2.uiuc-bdeep.org%2Fhub%2Foauth_callback&client_id=&response_type=code&state=eyJuZXh0X3VybCI6ICIiLCAic3RhdGVfaWQiOiAiZTdjNGU1YTkzZGU0NDViMGE4ZWU0NzY3ODY1Y2I1YmUifQ%3D%3D (@::ffff:141.142.60.194) 1.29ms

Also here is the oAuth application page, I dont think there is a problem there, but I would more than happy to be wrong: <img width="564" alt="screen shot 2018-06-07 at 11 11 24 am" src="https://user-images.githubusercontent.com/19716710/41112091-9822bfb6-6a43-11e8-8a42-2f32b921e8f4.png">

**Comment by betatim** [comment] 2018-06-07 17:50
Could you explain again what exactly the problem is? From your subject it sounds you end up on a 404 page (on GitHub or on the hub?) but from your text all you say is that the hub redicrects you to a github.com page which is exactly what should happen.

**Comment by Akmoore7** [comment] 2018-06-07 18:21
It redirects to a github page but it gave me this: 
<img width="1194" alt="screen shot 2018-06-07 at 1 20 27 pm" src="https://user-images.githubusercontent.com/19716710/41118458-9fe312ac-6a55-11e8-99b0-ae7242c4d5d0.png">

**Comment by Akmoore7** [comment] 2018-06-07 18:23
We actually figured out the issue, we had to add the client id and secret client id as well as the auth callback url in the env file. Then echoing the client id got me through to authorization, there is a new problem with the github users being unable to start a server though, a 500 internal server error on the page, and in logs it describes how the user could not be found "JupyterHub user:427] Unhandled error starting akmoore7's server: 'getpwnam(): name not found: akmoore7'"

**Comment by sblack4** [comment] 2018-11-14 13:32
For anyone else having this problem be wary of what authenticator you are using. The `MyOAuthenticator` is given as an example, not as an actual authenticator. for GitHub replace it with `GitHubOAuthenticator`

```
c.MyOAuthenticator.oauth_callback_url = 'https://jupyter2.uiuc-bdeep.org/hub/oauth_callback'
c.MyOAuthenticator.client_id = '7959f7faeee887a00c71'
c.MyOAuthenticator.client_secret = 'Client Secret'
c.Authenticator.whitelist = {'akmoore7','danielrychel' }
c.Authenticator.admin_users = {'Akmoore7','danielrychel'}
```
should be 
```
c.GitHubOAuthenticator.oauth_callback_url = 'https://jupyter2.uiuc-bdeep.org/hub/oauth_callback'
c.GitHubOAuthenticator.client_id = '7959f7faeee887a00c71'
c.GitHubOAuthenticator.client_secret = 'Client Secret'
c.Authenticator.whitelist = {'akmoore7','danielrychel' }
c.Authenticator.admin_users = {'Akmoore7','danielrychel'}
```

**Comment by orionjeong** [comment] 2019-01-30 09:48
Oh I made the same mistake. Some other examples give the correct information about the configuration, but github is missing. I think this should be added.

**Comment by ldnelso2** [comment] 2019-04-06 15:17
> We actually figured out the issue, we had to add the client id and secret client id as well as the auth callback url in the env file. Then echoing the client id got me through to authorization.

Hi AKmoore7 - can you elaborate on this approach?  I tried it but not working for me.

**Comment by liliarizona** [comment] 2019-10-13 06:58
> > We actually figured out the issue, we had to add the client id and secret client id as well as the auth callback url in the env file. Then echoing the client id got me through to authorization.
> 
> Hi AKmoore7 - can you elaborate on this approach? I tried it but not working for me.

I had the same issue, ended up fixing by (bolded texts were what's missing)
`
auth:
  type: github
  github:
    **clientId: "xxx"
    clientSecret: "xxxx"
    callbackUrl: "xxxx"**
    orgWhitelist:
      - "xxxx"
  scopes:
    - "read:user"
`

**Comment by iranika** [comment] 2019-10-29 06:00
I made a mistake :(
Added clientID, clientSecret, and callback to env file. But, Did not add to docekr-compose.yml

```docker-compose.yml
services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - OAUTH_CALLBACK_URL  //add
      - OAUTH_CLIENT_ID     //add
      - OAUTH_CLIENT_SECRET //add
      - HUB_IP=jupyterhub
      - HOST
```

**Comment by vishwa3** [comment] 2020-05-09 14:15
@sblack4 @liliarizona @iranika @betatim : If I hit the url in the browser (https://github.com/login/oauth/authorize?client_id=cc3cfe35c42118711e4) , I am getting a 404 whereas I am expecting the page asking for username/email and password . I also tried wrapping the clientID in quotes like [](https://github.com/login/oauth/authorize?client_id="cc3cfe35c42118711e4") but again I am getting a 404 - am I doing something wrong

**Comment by manics** [comment] 2020-10-13 19:32
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!

**Closed by manics** 2020-10-13 19:32 UTC

**Comment by Vinuram123** [comment] 2024-05-03 06:56
I am not using the clientId, below parameters I am passing
  const authorizationEndpoint = 'https://github.com/login/oauth/authorize';
    const redirectUri = 'https://www.google.com/';
    const scope = 'public_repo'; // Define required scopes
    const responseType = 'code';
    const state = this.generateRandomString(16); 
     I am getting the 404 page issue
