### ISSUE TITLE
github closes stream after token request

### ISSUE THREAD

**Issue by soldis** [jupyterhub/oauthenticator#246] opened 2019-03-10 23:53 UTC
When I try to authenticate using GitHubOAuthenticator I always get Exception "Stream closed".
It happens at step 2 of OAuth2 process - "https://github.com/login/oauth/authorize" executes normally and returns code, but when authenticator tries to fetch "https://github.com/login/oauth/access_token?client_id=..." exception is thrown. I found out that it happens in "tornado/simple_httpclient.py" when `_write_body` method tries to `await self.connection.read_response(self)`.

Although:
1) I tried to fetch other arbitrary URLs from within GitHubOAuthenticator' `authenticate` method - it works fine.
2) I tried to fetch GitHub's token manually with the help of curl - it works fine.
3) I even found and tried to use YandexPassportOAuthenticator which has almost identical code - it works fine!

Does anyone have any ideas why this can happen?

**Comment by kpfleming** [comment] 2019-06-06 14:40
I just setup this authenticator yesterday and I'm experiencing the same issue; did you find a solution?

**Comment by soldis** [comment] 2019-06-06 14:47
No, unfortunately, I didn't, although I followed and debugged each piece of code including network libraries -(
I decided to use Yandex authenticator and it works fine.

**Comment by kpfleming** [comment] 2019-06-06 15:53
Found the solution: the 'simple' HTTP client in Tornado doesn't work for the access_token request which is made to GitHub; configuring Tornado to use curl_httpclient instead (which requires installing pycurl as well) results in successful logins.

Adding these two lines to `jupyterhub_config.py` will take care of it:

```python
from tornado.httpclient import AsyncHTTPClient
AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")
```

**Comment by minrk** [comment] 2019-06-28 09:10
Do you have the output of `pip freeze`? I think this should be reported as a tornado bug if it can be reproducible.

**Comment by kpfleming** [comment] 2019-06-28 10:05
The only practical way to treat this as a bug would be for GitHubOAuthenticator to be published as its own package, with a dependency on `pycurl`. Otherwise the whole Tornado package would need a dependency on `pycurl` which would make installation of Tornado harder (since pycurl has native-package dependencies).

**Comment by minrk** [comment] 2019-06-28 10:25
I found the problem, and it's a tornado bug where simplehttpclient doesn't work right for certain requests when using old-style tornado coroutines instead of async def. The right fix is to switch to async def in this repo.

curl isn't relevant, except in that it avoids a bug in simplehttpclient when using old-style coroutines, which this repo still does.

**Comment by kpfleming** [comment] 2019-06-28 10:29
Nice work! Thanks for tracking that down. Feel free to comment on #270 that it can be closed in preference to your PR to change the simplehttpclient usage.

**Comment by minrk** [comment] 2019-06-28 10:37
Will do. And thanks for finding that curl is a valid workaround! Curl is indeed recommended in production if you have quite a few users, for performance reasons as well.

**Closed** 2019-06-28 11:44 UTC
